// AUTOMATICALLY GENERATED BY CMAKE. DO NOT MODIFY.
#ifndef HXGRAPHALGORITHMS_API_EXPORT_MACRO_H
#define HXGRAPHALGORITHMS_API_EXPORT_MACRO_H

#ifdef HXGRAPHALGORITHMS_STATIC
#   define HXGRAPHALGORITHMS_API
#else
#   ifdef _WIN32
#       ifdef HXGRAPHALGORITHMS_EXPORTS
#           define HXGRAPHALGORITHMS_API __declspec(dllexport)
#       else
#           define HXGRAPHALGORITHMS_API __declspec(dllimport)
#       endif
#   else
#       define HXGRAPHALGORITHMS_API __attribute__ ((visibility("default")))
#   endif
#endif

#endif
