# Amira Project 600
# Amira
# Generated by Amira 6.0.0-beta-3
remove -all
remove "grayScale.am" "physics.icol" "labels.am" "foam.am" "foam.thresholded" "foam.distmap" "foam.hMaxima" "foam.labels" "foam.not" "foam.watershed" "foam.sub" "foam2.labels" "foam2.surf" "foam.segmentation" "foam.to-labelfield-8_bits" "foam.surf" "Interactive Thresholding" "Chamfer Distance Map" "H-Maxima" "Labeling" "NOT" "Marker-Based Watershed" "AND NOT Image" "Labeling 2" "Generate Surface" "Surface View" "ContourTreeSegmentation" "Convert Image Type" "Generate Surface 2" "Surface View 2"

# Create viewers
viewer setVertical 1

viewer 0 setTransparencyType 6
viewer 0 setAutoRedraw 0
viewer 0 show
viewer 1 setTransparencyType 6
viewer 1 setAutoRedraw 0
viewer 1 show
mainWindow show

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/grayScale.am ] setLabel "grayScale.am"
"grayScale.am" setIconPosition 0 0
"grayScale.am" setNoRemoveAll 1
"grayScale.am" setVar "CustomHelp" {HxColormap256}
"grayScale.am" master disconnect
"grayScale.am" Datafield disconnect
"grayScale.am" fire
"grayScale.am" setMinMax 0 255
"grayScale.am" flags setValue 1
"grayScale.am" shift setMinMax -1 1
"grayScale.am" shift setButtons 0
"grayScale.am" shift setEditButton 1
"grayScale.am" shift setIncrement 0.133333
"grayScale.am" shift setValue 0
"grayScale.am" shift setSubMinMax -1 1
"grayScale.am" scale setMinMax 0 1
"grayScale.am" scale setButtons 0
"grayScale.am" scale setEditButton 1
"grayScale.am" scale setIncrement 0.1
"grayScale.am" scale setValue 1
"grayScale.am" scale setSubMinMax 0 1
"grayScale.am" fire
"grayScale.am" setViewerMask 65535

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" master disconnect
"physics.icol" Datafield disconnect
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 16383

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/labels.am ] setLabel "labels.am"
"labels.am" setIconPosition 0 0
"labels.am" setNoRemoveAll 1
"labels.am" setVar "CustomHelp" {HxColormap256}
"labels.am" master disconnect
"labels.am" Datafield disconnect
"labels.am" fire
"labels.am" setMinMax 1 8
"labels.am" flags setValue 1
"labels.am" shift setMinMax -1 1
"labels.am" shift setButtons 0
"labels.am" shift setEditButton 1
"labels.am" shift setIncrement 0.133333
"labels.am" shift setValue 0
"labels.am" shift setSubMinMax -1 1
"labels.am" scale setMinMax 0 1
"labels.am" scale setButtons 0
"labels.am" scale setEditButton 1
"labels.am" scale setIncrement 0.1
"labels.am" scale setValue 1
"labels.am" scale setSubMinMax 0 1
"labels.am" fire
"labels.am" setViewerMask 65535

set hideNewModules 0
[ load ${AMIRA_ROOT}/data/images/foam/foam.am ] setLabel "foam.am"
"foam.am" setIconPosition 20 10
"foam.am" master disconnect
"foam.am" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.am" sharedColormap setDefaultAlpha 0.500000
"foam.am" sharedColormap setLocalRange 1
"foam.am" sharedColormap setLocalMinMax 0.000000 1.000000
"foam.am" sharedColormap enableAlpha 1
"foam.am" sharedColormap enableAlphaToggle 1
"foam.am" sharedColormap setAutoAdjustRangeMode 1
"foam.am" sharedColormap disconnect
"foam.am" fire
"foam.am" setViewerMask 65535

set hideNewModules 0
create HxInteractiveThreshold "Interactive Thresholding"
"Interactive Thresholding" setViewerMask 0
"Interactive Thresholding" setIconPosition 160 10
"Interactive Thresholding" setVar "CustomHelp" {HxInteractiveThreshold}
set hideNewModules 0

"Interactive Thresholding" data connect "foam.am"
"Interactive Thresholding" mask disconnect
"Interactive Thresholding" inputColorMap setDefaultColor 1 0.8 0.5
"Interactive Thresholding" inputColorMap setDefaultAlpha 0.500000
"Interactive Thresholding" inputColorMap setLocalRange 1
"Interactive Thresholding" inputColorMap setLocalMinMax 82.000000 255.000000
"Interactive Thresholding" inputColorMap enableAlpha 1
"Interactive Thresholding" inputColorMap enableAlphaToggle 1
"Interactive Thresholding" inputColorMap setAutoAdjustRangeMode 1
"Interactive Thresholding" inputColorMap connect "grayScale.am"
"Interactive Thresholding" fire
"Interactive Thresholding" preview setValue 0 1
"Interactive Thresholding" preview setToggleVisible 0 1
"Interactive Thresholding" preview setValue 1 0
"Interactive Thresholding" preview setToggleVisible 1 1
"Interactive Thresholding" orientation setValue 0
"Interactive Thresholding" sliceNumber setMinMax 0 28
"Interactive Thresholding" sliceNumber setButtons 1
"Interactive Thresholding" sliceNumber setEditButton 1
"Interactive Thresholding" sliceNumber setIncrement 1
"Interactive Thresholding" sliceNumber setValue 14
"Interactive Thresholding" sliceNumber setSubMinMax 0 28
"Interactive Thresholding" rendering setValue 1
"Interactive Thresholding" intensityRange setMinMax 0 255
"Interactive Thresholding" intensityRange setValues 0 38
"Interactive Thresholding" intensityRange setButtons 0
"Interactive Thresholding" intensityRange setEditButton 1
"Interactive Thresholding" intensityRange setIncrement 17
"Interactive Thresholding" intensityRange setSubMinMax 0 0
"Interactive Thresholding" colorMask setColor 0 0 0 1
"Interactive Thresholding" applyTransformToResult 1
"Interactive Thresholding" fire
"Interactive Thresholding" setViewerMask 65532
"Interactive Thresholding" setPickable 1
"Interactive Thresholding" doIt snap 0 1

set hideNewModules 0
[ "Interactive Thresholding" doIt hit; "Interactive Thresholding" fire; "Interactive Thresholding" getResult
 ] setLabel "foam.thresholded"
"foam.thresholded" setIconPosition 20 46
"foam.thresholded" master connect "Interactive Thresholding" "result"
"foam.thresholded" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.thresholded" sharedColormap setDefaultAlpha 0.500000
"foam.thresholded" sharedColormap setLocalRange 1
"foam.thresholded" sharedColormap setLocalMinMax 1.000000 8.000000
"foam.thresholded" sharedColormap enableAlpha 1
"foam.thresholded" sharedColormap enableAlphaToggle 1
"foam.thresholded" sharedColormap setAutoAdjustRangeMode 1
"foam.thresholded" sharedColormap connect "labels.am"
"foam.thresholded" ImageData disconnect
"foam.thresholded" fire
"foam.thresholded" primary setIndex 0 0
"foam.thresholded" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"foam.thresholded" fire
"foam.thresholded" setViewerMask 65535

set hideNewModules 0
create dist557 "Chamfer Distance Map"
"Chamfer Distance Map" setIconPosition 160 82
"Chamfer Distance Map" setVar "CustomHelp" {distxxx.html}
"Chamfer Distance Map" interpretation setValue 0
"Chamfer Distance Map" outputLocation setIndex 0 0
"Chamfer Distance Map" inputImage connect "foam.thresholded"
"Chamfer Distance Map" faceDistance setMinMax 0 0 3.40282346638529e+38
"Chamfer Distance Map" faceDistance setValue 0 1
"Chamfer Distance Map" edgeDistance setMinMax 0 0 3.40282346638529e+38
"Chamfer Distance Map" edgeDistance setValue 0 1.41400003433228
"Chamfer Distance Map" cornerDistance setMinMax 0 0 3.40282346638529e+38
"Chamfer Distance Map" cornerDistance setValue 0 1.73000001907349
"Chamfer Distance Map" applyTransformToResult 1
"Chamfer Distance Map" fire
"Chamfer Distance Map" setViewerMask 65535
"Chamfer Distance Map" setPickable 1
"Chamfer Distance Map" doIt snap 0 1

set hideNewModules 0
#[ {Chamfer Distance Map} create ImgOut ] setLabel "foam.distmap"
[ {Chamfer Distance Map} doIt hit; {Chamfer Distance Map} fire; {Chamfer Distance Map} getResult
 ] setLabel "foam.distmap"
"foam.distmap" setIconPosition 20 82
"foam.distmap" master connect "Chamfer Distance Map" "ImgOut"
"foam.distmap" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.distmap" sharedColormap setDefaultAlpha 0.500000
"foam.distmap" sharedColormap setLocalRange 1
"foam.distmap" sharedColormap setLocalMinMax 0.000000 1.000000
"foam.distmap" sharedColormap enableAlpha 1
"foam.distmap" sharedColormap enableAlphaToggle 1
"foam.distmap" sharedColormap setAutoAdjustRangeMode 1
"foam.distmap" sharedColormap setColorbarMinMax 0 22
"foam.distmap" sharedColormap disconnect
"foam.distmap" fire
"foam.distmap" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"foam.distmap" fire
"foam.distmap" setViewerMask 65535

set hideNewModules 0
create merge_maxima "H-Maxima"
"H-Maxima" setIconPosition 160 154
"H-Maxima" setVar "CustomHelp" {merge_maxima.html}
"H-Maxima" interpretation setValue 0
"H-Maxima" outputLocation setIndex 0 0
"H-Maxima" neighborhood setValue 2
"H-Maxima" inputImage connect "foam.distmap"
"H-Maxima" contrast setMinMax 0 -2147483648 2147483648
"H-Maxima" contrast setValue 0 4
"H-Maxima" applyTransformToResult 1
"H-Maxima" fire
"H-Maxima" setViewerMask 65535
"H-Maxima" setPickable 1
"H-Maxima" doIt snap 0 1

set hideNewModules 0
#[ {H-Maxima} create ImgOutBin ] setLabel "foam.hMaxima"
[ {H-Maxima} doIt hit; {H-Maxima} fire; {H-Maxima} getResult
 ] setLabel "foam.hMaxima"
"foam.hMaxima" setIconPosition 20 154
"foam.hMaxima" master connect "H-Maxima" "ImgOutBin"
"foam.hMaxima" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.hMaxima" sharedColormap setDefaultAlpha 0.500000
"foam.hMaxima" sharedColormap setLocalRange 1
"foam.hMaxima" sharedColormap setLocalMinMax 1.000000 8.000000
"foam.hMaxima" sharedColormap enableAlpha 1
"foam.hMaxima" sharedColormap enableAlphaToggle 1
"foam.hMaxima" sharedColormap setAutoAdjustRangeMode 1
"foam.hMaxima" sharedColormap connect "labels.am"
"foam.hMaxima" ImageData disconnect
"foam.hMaxima" fire
"foam.hMaxima" primary setIndex 0 0
"foam.hMaxima" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"foam.hMaxima" fire
"foam.hMaxima" setViewerMask 65535

set hideNewModules 0
create label "Labeling"
"Labeling" setIconPosition 160 226
"Labeling" setVar "CustomHelp" {label.html}
"Labeling" interpretation setValue 0
"Labeling" outputLocation setIndex 0 0
"Labeling" neighborhood setValue 2
"Labeling" inputImage connect "foam.hMaxima"
"Labeling" applyTransformToResult 1
"Labeling" fire
"Labeling" setViewerMask 65535
"Labeling" setPickable 1
"Labeling" doIt snap 0 1

set hideNewModules 0
#[ {Labeling} create ImgOutLab ] setLabel "foam.labels"
[ {Labeling} doIt hit; {Labeling} fire; {Labeling} getResult
 ] setLabel "foam.labels"
"foam.labels" setIconPosition 20 226
"foam.labels" master connect "Labeling" "ImgOutLab"
"foam.labels" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.labels" sharedColormap setDefaultAlpha 0.500000
"foam.labels" sharedColormap setLocalRange 1
"foam.labels" sharedColormap setLocalMinMax 1.000000 8.000000
"foam.labels" sharedColormap enableAlpha 1
"foam.labels" sharedColormap enableAlphaToggle 1
"foam.labels" sharedColormap setAutoAdjustRangeMode 1
"foam.labels" sharedColormap setColorbarMinMax 1 8
"foam.labels" sharedColormap connect "labels.am"
"foam.labels" ImageData disconnect
"foam.labels" fire
"foam.labels" primary setIndex 0 0
"foam.labels" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"foam.labels" fire
"foam.labels" setViewerMask 65535

set hideNewModules 0
create logical_not "NOT"
"NOT" setIconPosition 160 190
"NOT" setVar "CustomHelp" {logical_not.html}
"NOT" interpretation setValue 0
"NOT" outputLocation setIndex 0 0
"NOT" inputImage connect "foam.distmap"
"NOT" applyTransformToResult 1
"NOT" fire
"NOT" setViewerMask 65535
"NOT" setPickable 1
"NOT" doIt snap 0 1

set hideNewModules 0
#[ {NOT} create ImgOut ] setLabel "foam.not"
[ {NOT} doIt hit; {NOT} fire; {NOT} getResult
 ] setLabel "foam.not"
"foam.not" setIconPosition 20 190
"foam.not" master connect "NOT" "ImgOut"
"foam.not" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.not" sharedColormap setDefaultAlpha 0.500000
"foam.not" sharedColormap setLocalRange 1
"foam.not" sharedColormap setLocalMinMax 0.000000 1.000000
"foam.not" sharedColormap enableAlpha 1
"foam.not" sharedColormap enableAlphaToggle 1
"foam.not" sharedColormap setAutoAdjustRangeMode 1
"foam.not" sharedColormap disconnect
"foam.not" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"foam.not" fire
"foam.not" setViewerMask 65535

set hideNewModules 0
create fastwatershed "Marker-Based Watershed"
"Marker-Based Watershed" setIconPosition 160 262
"Marker-Based Watershed" setVar "CustomHelp" {fastwatershed.html}
"Marker-Based Watershed" Type setState {type Watershed}
"Marker-Based Watershed" interpretation setValue 0
"Marker-Based Watershed" outputLocation setIndex 0 0
"Marker-Based Watershed" neighborhood setValue 2
"Marker-Based Watershed" inputGrayscaleImage connect "foam.not"
"Marker-Based Watershed" inputLabelImage connect "foam.labels"
"Marker-Based Watershed" algorithmMode setIndex 0 0
"Marker-Based Watershed" applyTransformToResult 1
"Marker-Based Watershed" fire
"Marker-Based Watershed" setViewerMask 65535
"Marker-Based Watershed" setPickable 1
"Marker-Based Watershed" doIt snap 0 1

set hideNewModules 0
#[ {Marker-Based Watershed} create ImgOutBin ] setLabel "foam.watershed"
[ {Marker-Based Watershed} doIt hit; {Marker-Based Watershed} fire; {Marker-Based Watershed} getResult
 ] setLabel "foam.watershed"
"foam.watershed" setIconPosition 20 298
"foam.watershed" master connect "Marker-Based Watershed" "ImgOutBin"
"foam.watershed" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.watershed" sharedColormap setDefaultAlpha 0.500000
"foam.watershed" sharedColormap setLocalRange 1
"foam.watershed" sharedColormap setLocalMinMax 1.000000 8.000000
"foam.watershed" sharedColormap enableAlpha 1
"foam.watershed" sharedColormap enableAlphaToggle 1
"foam.watershed" sharedColormap setAutoAdjustRangeMode 1
"foam.watershed" sharedColormap setColorbarMinMax 1 8
"foam.watershed" sharedColormap connect "labels.am"
"foam.watershed" ImageData disconnect
"foam.watershed" fire
"foam.watershed" primary setIndex 0 0
"foam.watershed" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"foam.watershed" fire
"foam.watershed" setViewerMask 65535

set hideNewModules 0
create logical_subimage "AND NOT Image"
"AND NOT Image" setIconPosition 160 118
"AND NOT Image" setVar "CustomHelp" {logical_subimage.html}
"AND NOT Image" interpretation setValue 0
"AND NOT Image" outputLocation setIndex 0 0
"AND NOT Image" inputImage1 connect "foam.thresholded"
"AND NOT Image" inputImage2 connect "foam.watershed"
"AND NOT Image" applyTransformToResult 1
"AND NOT Image" fire
"AND NOT Image" setViewerMask 65535
"AND NOT Image" setPickable 1
"AND NOT Image" doIt snap 0 1

set hideNewModules 0
#[ {AND NOT Image} create ImgOut ] setLabel "foam.sub"
[ {AND NOT Image} doIt hit; {AND NOT Image} fire; {AND NOT Image} getResult
 ] setLabel "foam.sub"
"foam.sub" setIconPosition 20 118
"foam.sub" master connect "AND NOT Image" "ImgOut"
"foam.sub" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.sub" sharedColormap setDefaultAlpha 0.500000
"foam.sub" sharedColormap setLocalRange 1
"foam.sub" sharedColormap setLocalMinMax 1.000000 8.000000
"foam.sub" sharedColormap enableAlpha 1
"foam.sub" sharedColormap enableAlphaToggle 1
"foam.sub" sharedColormap setAutoAdjustRangeMode 1
"foam.sub" sharedColormap connect "labels.am"
"foam.sub" ImageData disconnect
"foam.sub" fire
"foam.sub" primary setIndex 0 0
"foam.sub" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"foam.sub" fire
"foam.sub" setViewerMask 65535

set hideNewModules 0
create label "Labeling 2"
"Labeling 2" setIconPosition 160 334
"Labeling 2" setVar "CustomHelp" {label.html}
"Labeling 2" interpretation setValue 0
"Labeling 2" outputLocation setIndex 0 0
"Labeling 2" neighborhood setValue 2
"Labeling 2" inputImage connect "foam.sub"
"Labeling 2" applyTransformToResult 1
"Labeling 2" fire
"Labeling 2" setViewerMask 65535
"Labeling 2" setPickable 1
"Labeling 2" doIt snap 0 1

set hideNewModules 0
#[ {Labeling 2} create ImgOutLab ] setLabel "foam2.labels"
[ {Labeling 2} doIt hit; {Labeling 2} fire; {Labeling 2} getResult
 ] setLabel "foam2.labels"
"foam2.labels" setIconPosition 20 334
"foam2.labels" master connect "Labeling 2" "ImgOutLab"
"foam2.labels" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam2.labels" sharedColormap setDefaultAlpha 0.500000
"foam2.labels" sharedColormap setLocalRange 1
"foam2.labels" sharedColormap setLocalMinMax 1.000000 8.000000
"foam2.labels" sharedColormap enableAlpha 1
"foam2.labels" sharedColormap enableAlphaToggle 1
"foam2.labels" sharedColormap setAutoAdjustRangeMode 1
"foam2.labels" sharedColormap setColorbarMinMax 1 8
"foam2.labels" sharedColormap connect "labels.am"
"foam2.labels" ImageData disconnect
"foam2.labels" fire
"foam2.labels" primary setIndex 0 0
"foam2.labels" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"foam2.labels" fire
"foam2.labels" setViewerMask 65535

set hideNewModules 0
create HxGMC "Generate Surface"
"Generate Surface" setIconPosition 160 370
"Generate Surface" setVar "CustomHelp" {HxGMC}
"Generate Surface" data connect "foam2.labels"
"Generate Surface" fire
"Generate Surface" smoothing setIndex 0 2
"Generate Surface" smoothingExtent setMinMax 1 9
"Generate Surface" smoothingExtent setButtons 0
"Generate Surface" smoothingExtent setEditButton 1
"Generate Surface" smoothingExtent setIncrement 0.533333
"Generate Surface" smoothingExtent setValue 5
"Generate Surface" smoothingExtent setSubMinMax 1 9
"Generate Surface" options setValue 0 1
"Generate Surface" options setToggleVisible 0 1
"Generate Surface" options setValue 1 0
"Generate Surface" options setToggleVisible 1 1
"Generate Surface" border setValue 0 1
"Generate Surface" border setToggleVisible 0 1
"Generate Surface" border setValue 1 0
"Generate Surface" border setToggleVisible 1 1
"Generate Surface" border setValue 2 0
"Generate Surface" border setToggleVisible 2 1
"Generate Surface" border setValue 3 0
"Generate Surface" border setToggleVisible 3 1
"Generate Surface" minEdgeLength setMinMax 0 0 0.800000011920929
"Generate Surface" minEdgeLength setValue 0 0
"Generate Surface" materialList setIndex 0 0
"Generate Surface" smoothMaterial setIndex 0 0
"Generate Surface" applyTransformToResult 1
"Generate Surface" fire
"Generate Surface" setViewerMask 16383
"Generate Surface" setPickable 1

set hideNewModules 0
[ "Generate Surface" create "foam2.surf"
 ] setLabel "foam2.surf"
"foam2.surf" setIconPosition 20 370
"foam2.surf" master connect "Generate Surface" "result"
"foam2.surf" fire
"foam2.surf" LevelOfDetail setMinMax -1 -1
"foam2.surf" LevelOfDetail setButtons 1
"foam2.surf" LevelOfDetail setEditButton 1
"foam2.surf" LevelOfDetail setIncrement 1
"foam2.surf" LevelOfDetail setValue -1
"foam2.surf" LevelOfDetail setSubMinMax -1 -1
"foam2.surf" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"foam2.surf" fire
"foam2.surf" setViewerMask 16383

set hideNewModules 0
create HxDisplaySurface "Surface View"
"Surface View" setIconPosition 311 370
"Surface View" setVar "CustomHelp" {HxDisplaySurface}
"Surface View" data connect "foam2.surf"
"Surface View" colorField disconnect
"Surface View" colormap setDefaultColor 1 0.1 0.1
"Surface View" colormap setDefaultAlpha 0.500000
"Surface View" colormap setLocalRange 1
"Surface View" colormap setLocalMinMax 0.000000 1.000000
"Surface View" colormap enableAlpha 1
"Surface View" colormap enableAlphaToggle 1
"Surface View" colormap setAutoAdjustRangeMode 1
"Surface View" colormap setColorbarMinMax 0 1
"Surface View" colormap disconnect
"Surface View" Texture disconnect
"Surface View" ROI disconnect
"Surface View" fire
"Surface View" drawStyle setValue 1
"Surface View" fire
"Surface View" drawStyle setSpecularLighting 1
"Surface View" drawStyle setTexture 1
"Surface View" drawStyle setAlphaMode 1
"Surface View" drawStyle setNormalBinding 0
"Surface View" drawStyle setSortingMode 1
"Surface View" drawStyle setLineWidth 0.000000
"Surface View" drawStyle setOutlineColor 0 0 0.2
"Surface View" textureWrap setIndex 0 1
"Surface View" cullingMode setValue 0
"Surface View" selectionMode setIndex 0 0
"Surface View" Patch setMinMax 0 235
"Surface View" Patch setButtons 1
"Surface View" Patch setEditButton 1
"Surface View" Patch setIncrement 1
"Surface View" Patch setValue 0
"Surface View" Patch setSubMinMax 0 235
"Surface View" BoundaryId setIndex 0 -1
"Surface View" materials setIndex 0 1
"Surface View" materials setIndex 1 0
"Surface View" colorMode setIndex 0 0
"Surface View" baseTrans setMinMax 0 1
"Surface View" baseTrans setButtons 0
"Surface View" baseTrans setEditButton 1
"Surface View" baseTrans setIncrement 0.1
"Surface View" baseTrans setValue 0.8
"Surface View" baseTrans setSubMinMax 0 1
"Surface View" VRMode setIndex 0 0
"Surface View" colorFieldMappingType setValue 0
"Surface View" setLighting 1
"Surface View" fire
"Surface View" hideBox 1
"Surface View" selectTriangles zab HIJMONMBDBABAAAAAIMACABLNIDPONKMOBABBEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAMJGMBNKMOMEDLB
"Surface View" fire
"Surface View" setViewerMask 16381
"Surface View" setShadowStyle 0
"Surface View" setPickable 1

set hideNewModules 0
create HxContourTreeSegmentation "ContourTreeSegmentation"
"ContourTreeSegmentation" setIconPosition 160 406
"ContourTreeSegmentation" setVar "CustomHelp" {HxContourTreeSegmentation}
"ContourTreeSegmentation" data connect "foam.distmap"
"ContourTreeSegmentation" fire
"ContourTreeSegmentation" auto-initialization setValue 0 1
"ContourTreeSegmentation" auto-initialization setToggleVisible 0 1
"ContourTreeSegmentation" threshold setMinMax 0 22
"ContourTreeSegmentation" threshold setButtons 0
"ContourTreeSegmentation" threshold setEditButton 1
"ContourTreeSegmentation" threshold setIncrement 1.46667
"ContourTreeSegmentation" threshold setValue 0.001
"ContourTreeSegmentation" threshold setSubMinMax 0 22
"ContourTreeSegmentation" persistenceMode setValue 0
"ContourTreeSegmentation" persistenceOptions setValue 0
"ContourTreeSegmentation" persistenceValue setMinMax 0 22
"ContourTreeSegmentation" persistenceValue setButtons 0
"ContourTreeSegmentation" persistenceValue setEditButton 1
"ContourTreeSegmentation" persistenceValue setIncrement 1.46667
"ContourTreeSegmentation" persistenceValue setValue 1
"ContourTreeSegmentation" persistenceValue setSubMinMax 0 22
"ContourTreeSegmentation" sortNeighborsBy setValue 1
"ContourTreeSegmentation" fastSegmentation setValue 0 1
"ContourTreeSegmentation" fastSegmentation setToggleVisible 0 1
"ContourTreeSegmentation" applyTransformToResult 1
"ContourTreeSegmentation" fire
"ContourTreeSegmentation" setViewerMask 16383
"ContourTreeSegmentation" select
"ContourTreeSegmentation" setPickable 1
"ContourTreeSegmentation" doIt snap 0 1

set hideNewModules 0
#[ {ContourTreeSegmentation} create result ] setLabel "foam.segmentation"
[ {ContourTreeSegmentation} doIt hit; {ContourTreeSegmentation} fire; {ContourTreeSegmentation} getResult
 ] setLabel "foam.segmentation"
"foam.segmentation" setIconPosition 20 442
"foam.segmentation" master connect "ContourTreeSegmentation" "result"
"foam.segmentation" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.segmentation" sharedColormap setDefaultAlpha 0.500000
"foam.segmentation" sharedColormap setLocalRange 1
"foam.segmentation" sharedColormap setLocalMinMax 0.000000 1.000000
"foam.segmentation" sharedColormap enableAlpha 1
"foam.segmentation" sharedColormap enableAlphaToggle 1
"foam.segmentation" sharedColormap setAutoAdjustRangeMode 1
"foam.segmentation" sharedColormap setColorbarMinMax 0 119
"foam.segmentation" sharedColormap disconnect
"foam.segmentation" fire
"foam.segmentation" fire
"foam.segmentation" setViewerMask 16383

set hideNewModules 0
create HxCastField "Convert Image Type"
"Convert Image Type" setIconPosition 160 478
"Convert Image Type" setVar "CustomHelp" {HxCastField}
"Convert Image Type" data connect "foam.segmentation"
"Convert Image Type" colormap setDefaultColor 1 0.8 0.5
"Convert Image Type" colormap setDefaultAlpha 0.500000
"Convert Image Type" colormap setLocalRange 1
"Convert Image Type" colormap setLocalMinMax 0.000000 119.000000
"Convert Image Type" colormap enableAlpha 1
"Convert Image Type" colormap enableAlphaToggle 1
"Convert Image Type" colormap setAutoAdjustRangeMode 1
"Convert Image Type" colormap setColorbarMinMax 0 119
"Convert Image Type" colormap disconnect
"Convert Image Type" fire
"Convert Image Type" outputType setIndex 0 6
"Convert Image Type" scaling setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
"Convert Image Type" scaling setValue 0 1
"Convert Image Type" scaling setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
"Convert Image Type" scaling setValue 1 0
"Convert Image Type" voxelGridOptions setValue 0 1
"Convert Image Type" voxelGridOptions setToggleVisible 0 1
"Convert Image Type" colorFieldOptions setIndex 0 0
"Convert Image Type" applyTransformToResult 1
"Convert Image Type" fire
"Convert Image Type" setViewerMask 16383
"Convert Image Type" setPickable 1
"Convert Image Type" action snap 0 1

set hideNewModules 0
[ {Convert Image Type} create result ] setLabel "foam.to-labelfield-8_bits"
"foam.to-labelfield-8_bits" setIconPosition 20 514
"foam.to-labelfield-8_bits" master connect "Convert Image Type" "result"
"foam.to-labelfield-8_bits" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.to-labelfield-8_bits" sharedColormap setDefaultAlpha 0.500000
"foam.to-labelfield-8_bits" sharedColormap setLocalRange 1
"foam.to-labelfield-8_bits" sharedColormap setLocalMinMax 1.000000 8.000000
"foam.to-labelfield-8_bits" sharedColormap enableAlpha 1
"foam.to-labelfield-8_bits" sharedColormap enableAlphaToggle 1
"foam.to-labelfield-8_bits" sharedColormap setAutoAdjustRangeMode 1
"foam.to-labelfield-8_bits" sharedColormap setColorbarMinMax 1 8
"foam.to-labelfield-8_bits" sharedColormap connect "labels.am"
"foam.to-labelfield-8_bits" ImageData disconnect
"foam.to-labelfield-8_bits" fire
"foam.to-labelfield-8_bits" primary setIndex 0 0
"foam.to-labelfield-8_bits" fire
"foam.to-labelfield-8_bits" setViewerMask 16383

set hideNewModules 0
create HxGMC "Generate Surface 2"
"Generate Surface 2" setIconPosition 160 550
"Generate Surface 2" setVar "CustomHelp" {HxGMC}
"Generate Surface 2" data connect "foam.to-labelfield-8_bits"
"Generate Surface 2" fire
"Generate Surface 2" smoothing setIndex 0 2
"Generate Surface 2" smoothingExtent setMinMax 1 9
"Generate Surface 2" smoothingExtent setButtons 0
"Generate Surface 2" smoothingExtent setEditButton 1
"Generate Surface 2" smoothingExtent setIncrement 0.533333
"Generate Surface 2" smoothingExtent setValue 5
"Generate Surface 2" smoothingExtent setSubMinMax 1 9
"Generate Surface 2" options setValue 0 1
"Generate Surface 2" options setToggleVisible 0 1
"Generate Surface 2" options setValue 1 0
"Generate Surface 2" options setToggleVisible 1 1
"Generate Surface 2" border setValue 0 1
"Generate Surface 2" border setToggleVisible 0 1
"Generate Surface 2" border setValue 1 0
"Generate Surface 2" border setToggleVisible 1 1
"Generate Surface 2" border setValue 2 0
"Generate Surface 2" border setToggleVisible 2 1
"Generate Surface 2" border setValue 3 0
"Generate Surface 2" border setToggleVisible 3 1
"Generate Surface 2" minEdgeLength setMinMax 0 0 0.800000011920929
"Generate Surface 2" minEdgeLength setValue 0 0
"Generate Surface 2" materialList setIndex 0 0
"Generate Surface 2" smoothMaterial setIndex 0 0
"Generate Surface 2" applyTransformToResult 1
"Generate Surface 2" fire
"Generate Surface 2" setViewerMask 16383
"Generate Surface 2" setPickable 1
"Generate Surface 2" action snap 0 1

set hideNewModules 0
[ "Generate Surface 2" create "foam.surf"
 ] setLabel "foam.surf"
"foam.surf" setIconPosition 20 550
"foam.surf" master connect "Generate Surface 2" "result"
"foam.surf" fire
"foam.surf" LevelOfDetail setMinMax -1 -1
"foam.surf" LevelOfDetail setButtons 1
"foam.surf" LevelOfDetail setEditButton 1
"foam.surf" LevelOfDetail setIncrement 1
"foam.surf" LevelOfDetail setValue -1
"foam.surf" LevelOfDetail setSubMinMax -1 -1
"foam.surf" fire
"foam.surf" setViewerMask 16383

set hideNewModules 0
create HxDisplaySurface "Surface View 2"
"Surface View 2" setIconPosition 363 550
"Surface View 2" setVar "CustomHelp" {HxDisplaySurface}
"Surface View 2" data connect "foam.surf"
"Surface View 2" colorField disconnect
"Surface View 2" colormap setDefaultColor 1 0.1 0.1
"Surface View 2" colormap setDefaultAlpha 0.500000
"Surface View 2" colormap setLocalRange 1
"Surface View 2" colormap setLocalMinMax 0.000000 1.000000
"Surface View 2" colormap enableAlpha 1
"Surface View 2" colormap enableAlphaToggle 1
"Surface View 2" colormap setAutoAdjustRangeMode 1
"Surface View 2" colormap setColorbarMinMax 0 1
"Surface View 2" colormap disconnect
"Surface View 2" Texture disconnect
"Surface View 2" ROI disconnect
"Surface View 2" fire
"Surface View 2" drawStyle setValue 1
"Surface View 2" fire
"Surface View 2" drawStyle setSpecularLighting 1
"Surface View 2" drawStyle setTexture 1
"Surface View 2" drawStyle setAlphaMode 1
"Surface View 2" drawStyle setNormalBinding 0
"Surface View 2" drawStyle setSortingMode 1
"Surface View 2" drawStyle setLineWidth 0.000000
"Surface View 2" drawStyle setOutlineColor 0 0 0.2
"Surface View 2" textureWrap setIndex 0 1
"Surface View 2" cullingMode setValue 0
"Surface View 2" selectionMode setIndex 0 0
"Surface View 2" Patch setMinMax 0 481
"Surface View 2" Patch setButtons 1
"Surface View 2" Patch setEditButton 1
"Surface View 2" Patch setIncrement 1
"Surface View 2" Patch setValue 0
"Surface View 2" Patch setSubMinMax 0 481
"Surface View 2" BoundaryId setIndex 0 -1
"Surface View 2" materials setIndex 0 1
"Surface View 2" materials setIndex 1 0
"Surface View 2" colorMode setIndex 0 0
"Surface View 2" baseTrans setMinMax 0 1
"Surface View 2" baseTrans setButtons 0
"Surface View 2" baseTrans setEditButton 1
"Surface View 2" baseTrans setIncrement 0.1
"Surface View 2" baseTrans setValue 0.8
"Surface View 2" baseTrans setSubMinMax 0 1
"Surface View 2" VRMode setIndex 0 0
"Surface View 2" colorFieldMappingType setValue 0
"Surface View 2" setLighting 1
"Surface View 2" fire
"Surface View 2" hideBox 1
"Surface View 2" selectTriangles zab HIJMONNNEBFCODDABAAAMAKBHCOAMIBDHIAKEPALEPPDFDHIACMHBMCIGGJFGFJHANNJBAJMNILBGELLPLEEFBFECBMLODJBGEMJFCCGAANEBFBBAPHBCALDILNKGFACAAIALFIKONOPDOPKJPLOPJLDLOPJEMEELJHBHBEGPJJDFNONDCACLAHMHBJHNPLGEHKJCNOCIMIIMHPPGCCHHHKBCPAKCMFCMEPNNJPBNLNHPGNDLIBMAAFIJGDCPMOLNNBHKKKJBEPFLNHGFNABAAMABKJFOOPIGDONPBMADJOGKPAAGAJILIDPFIKDPMKOFNAFAAAAAANKBFAPODKMHDMKMODLBAKGBHCFIAMHIINPMPDILGBHBIAACLPEJEAHPDFKPKHEAAFFEENMENPKANFCPKJGGIHFAONHLBBMMFMCELONLCABAAMAFABBEPJJGPNOGLMBFEEOMNNBJGFPLPNGCOBHAANAJOHNDHOBOGJDBOBHCIEFHKKLFNCHAAAAAAKMEHBJIKDONEBOALFPKCALPDGNMALIPGFDPJNPOFJMDELPAIAAKDIIMNOFHLIFLMOKPLADEHOCMENMLOFMDBMMLJDMJMMGEDCMNMDOMKDPODPNFFCOABGIENEJMPEPJHIOCDAPLNOJCHACCDNLCHJFCBHJOJFICHEPNBDAPBAKMANONPLDAAMKIPFNONLCAALABOJHIMLPONENAONDDJDOCHGKEJHLKIDNOFPAPHHOGJHNMFACHFAPLFELLAFEHPNLPKDENGIECPCCDGBHLFEHBPCLJPOGOPHAPNNGPFONPAFLHDHFNBKPNMMLNLFLGKNPHIPGLNGPNGHEMAPPMGMIIJLHNGGCMOAFKABNHNMGDFMHGDJJPIGBAPNINPHPEAPDMGFOFLNJIHLDNMKBJPENLGDPMOGIFBDOGLHPGAOPCONLMNCBPJOODJAFDICFBOIPNGPHMIJHMAMMGMLDNNDOOINKOEEOBLACGDCLIPNGHNONGHPLCFDMNLFMGGHPPGPKJIDBGIIPDHIANLIJABGHPANKMPHHFOGCOCHDKFMEAHLEGDMKGHHPAMFJAGAALFOLAMOGMONKKPPODCJPOFBMFILIGNMKIJHNHJAPNLKGDCJMLPDKIGLLHAEPGLBJHLJOOEFKPJPBNJAOHMHLGGEHBHPCAEPEHFOOMMHCLJHJDNGKLGPBCJHGIAADNHJMONHNCLLJMALNNABIPGDOOCHEJMLEDNPPDHOGLFNOMKJCPGHBOGLGMGBKLLJMINEHHLMJKNMGBEPBPEHNJMNJBLGIOJGCMANKNFOBPBOFDMIADJCILHGKFDCLEGIGLCPHNNGJFDLFCLJNPKFPINJKHNJFFGLFLKOOKDOPPJAJKNLPDPKALPKJJPMPCFIOBPMGNOGLNOPHDNLHBBDDOOLDKOMJBCHDMECJDFPGHGHGFOAMLFINLBIGEDBPHEJIGLPHJMMNNMKJPHBLCJNFPLDIPELJJINLHNCMEFNJIOHHENPJFOPLHKFKDFNGBONDCPDBLPPOEDPMBAGDHDLMKGNGPNFEOHEDJFHPLBKLHFGNNLPEEOHDOJLKPIMIAJPPMOFLLGLOACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKACFBBJLPMAFFAAFKIIB
"Surface View 2" fire
"Surface View 2" setViewerMask 16382
"Surface View 2" setShadowStyle 0
"Surface View 2" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation -0.9043 0.360362 -0.22887 2.15633
viewer 0 setCameraPosition 381.62 397.442 -147.567
viewer 0 setCameraFocalDistance 411.492
viewer 0 setCameraNearDistance 243.672
viewer 0 setCameraFarDistance 568.597
viewer 0 setCameraType perspective
viewer 0 setCameraHeightAngle 44.9023
viewer 0 linkViewer 1
viewer 0 setAutoRedraw 1
viewer 0 redraw

viewer 1 setCameraOrientation -0.9043 0.360362 -0.22887 2.15633
viewer 1 setCameraPosition 381.62 397.442 -147.567
viewer 1 setCameraFocalDistance 411.492
viewer 1 setCameraNearDistance 243.672
viewer 1 setCameraFarDistance 568.597
viewer 1 setCameraType perspective
viewer 1 setCameraHeightAngle 44.9023
viewer 1 setAutoRedraw 1
viewer 1 redraw

"Interactive Thresholding" sliceNumber interconnect "Interactive Thresholding_HxOrthoSlice" sliceNumber
theObjectPool setSelectionOrder ContourTreeSegmentation
