# Amira Project 600
# Amira
# Generated by Amira 6.0.0-beta-3
remove -all
remove "grayScale.am" "physics.icol" "labels.am" "foam.am" "foam.thresholded" "foam.DistField" "foam.segmentation" "foam.to-labelfield-16_bits" "foam.surf" "Interactive Thresholding" "Distance Map" "ContourTreeSegmentation" "Convert Image Type" "Generate Surface" "Surface View"

# Create viewers
viewer setVertical 1

viewer 1 setTransparencyType 6
viewer 1 setAutoRedraw 0
viewer 1 show
mainWindow show

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/grayScale.am ] setLabel "grayScale.am"
"grayScale.am" setIconPosition 0 0
"grayScale.am" setNoRemoveAll 1
"grayScale.am" setVar "CustomHelp" {HxColormap256}
"grayScale.am" master disconnect
"grayScale.am" Datafield disconnect
"grayScale.am" fire
"grayScale.am" setMinMax 0 255
"grayScale.am" flags setValue 1
"grayScale.am" shift setMinMax -1 1
"grayScale.am" shift setButtons 0
"grayScale.am" shift setEditButton 1
"grayScale.am" shift setIncrement 0.133333
"grayScale.am" shift setValue 0
"grayScale.am" shift setSubMinMax -1 1
"grayScale.am" scale setMinMax 0 1
"grayScale.am" scale setButtons 0
"grayScale.am" scale setEditButton 1
"grayScale.am" scale setIncrement 0.1
"grayScale.am" scale setValue 1
"grayScale.am" scale setSubMinMax 0 1
"grayScale.am" fire
"grayScale.am" setViewerMask 65535

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" master disconnect
"physics.icol" Datafield disconnect
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 16383

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/labels.am ] setLabel "labels.am"
"labels.am" setIconPosition 0 0
"labels.am" setNoRemoveAll 1
"labels.am" setVar "CustomHelp" {HxColormap256}
"labels.am" master disconnect
"labels.am" Datafield disconnect
"labels.am" fire
"labels.am" setMinMax 1 8
"labels.am" flags setValue 1
"labels.am" shift setMinMax -1 1
"labels.am" shift setButtons 0
"labels.am" shift setEditButton 1
"labels.am" shift setIncrement 0.133333
"labels.am" shift setValue 0
"labels.am" shift setSubMinMax -1 1
"labels.am" scale setMinMax 0 1
"labels.am" scale setButtons 0
"labels.am" scale setEditButton 1
"labels.am" scale setIncrement 0.1
"labels.am" scale setValue 1
"labels.am" scale setSubMinMax 0 1
"labels.am" fire
"labels.am" setViewerMask 65535

set hideNewModules 0
[ load ${AMIRA_ROOT}/data/images/foam/foam.am ] setLabel "foam.am"
"foam.am" setIconPosition 20 10
"foam.am" master disconnect
"foam.am" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.am" sharedColormap setDefaultAlpha 0.500000
"foam.am" sharedColormap setLocalRange 1
"foam.am" sharedColormap setLocalMinMax 0.000000 1.000000
"foam.am" sharedColormap enableAlpha 1
"foam.am" sharedColormap enableAlphaToggle 1
"foam.am" sharedColormap setAutoAdjustRangeMode 1
"foam.am" sharedColormap disconnect
"foam.am" fire
"foam.am" setViewerMask 65535

set hideNewModules 0
create HxInteractiveThreshold "Interactive Thresholding"
"Interactive Thresholding" setViewerMask 0
"Interactive Thresholding" setIconPosition 160 10
"Interactive Thresholding" setVar "CustomHelp" {HxInteractiveThreshold}
set hideNewModules 0

"Interactive Thresholding" data connect "foam.am"
"Interactive Thresholding" mask disconnect
"Interactive Thresholding" inputColorMap setDefaultColor 1 0.8 0.5
"Interactive Thresholding" inputColorMap setDefaultAlpha 0.500000
"Interactive Thresholding" inputColorMap setLocalRange 1
"Interactive Thresholding" inputColorMap setLocalMinMax 82.000000 255.000000
"Interactive Thresholding" inputColorMap enableAlpha 1
"Interactive Thresholding" inputColorMap enableAlphaToggle 1
"Interactive Thresholding" inputColorMap setAutoAdjustRangeMode 1
"Interactive Thresholding" inputColorMap connect "grayScale.am"
"Interactive Thresholding" fire
"Interactive Thresholding" preview setValue 0 1
"Interactive Thresholding" preview setToggleVisible 0 1
"Interactive Thresholding" preview setValue 1 0
"Interactive Thresholding" preview setToggleVisible 1 1
"Interactive Thresholding" orientation setValue 0
"Interactive Thresholding" sliceNumber setMinMax 0 28
"Interactive Thresholding" sliceNumber setButtons 1
"Interactive Thresholding" sliceNumber setEditButton 1
"Interactive Thresholding" sliceNumber setIncrement 1
"Interactive Thresholding" sliceNumber setValue 14
"Interactive Thresholding" sliceNumber setSubMinMax 0 28
"Interactive Thresholding" rendering setValue 1
"Interactive Thresholding" intensityRange setMinMax 0 255
"Interactive Thresholding" intensityRange setValues 0 38
"Interactive Thresholding" intensityRange setButtons 0
"Interactive Thresholding" intensityRange setEditButton 1
"Interactive Thresholding" intensityRange setIncrement 17
"Interactive Thresholding" intensityRange setSubMinMax 0 0
"Interactive Thresholding" colorMask setColor 0 0 0 1
"Interactive Thresholding" applyTransformToResult 1
"Interactive Thresholding" fire
"Interactive Thresholding" setViewerMask 65532
"Interactive Thresholding" setPickable 1
"Interactive Thresholding" doIt snap 0 1

set hideNewModules 0
[ "Interactive Thresholding" doIt hit; "Interactive Thresholding" fire; "Interactive Thresholding" getResult
 ] setLabel "foam.thresholded"
"foam.thresholded" setIconPosition 20 46
"foam.thresholded" master connect "Interactive Thresholding" "result"
"foam.thresholded" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.thresholded" sharedColormap setDefaultAlpha 0.500000
"foam.thresholded" sharedColormap setLocalRange 1
"foam.thresholded" sharedColormap setLocalMinMax 1.000000 8.000000
"foam.thresholded" sharedColormap enableAlpha 1
"foam.thresholded" sharedColormap enableAlphaToggle 1
"foam.thresholded" sharedColormap setAutoAdjustRangeMode 1
"foam.thresholded" sharedColormap setColorbarMinMax 1 8
"foam.thresholded" sharedColormap connect "labels.am"
"foam.thresholded" ImageData disconnect
"foam.thresholded" fire
"foam.thresholded" primary setIndex 0 0
"foam.thresholded" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"foam.thresholded" fire
"foam.thresholded" setViewerMask 65535

set hideNewModules 0
create HxComputeDistanceMap "Distance Map"
"Distance Map" setIconPosition 160 82
"Distance Map" setVar "CustomHelp" {HxComputeDistanceMap}
"Distance Map" data connect "foam.thresholded"
"Distance Map" fire
"Distance Map" type setValue 0
"Distance Map" chamferMetric setValue 1
"Distance Map" region setIndex 0 0
"Distance Map" seed  setBoundingBox 1 250 1 250 1 29
"Distance Map" seed  setImmediate 0
"Distance Map" seed  setOrtho 0
"Distance Map" seed  showDragger 0
"Distance Map" seed  showPoints 0
"Distance Map" seed  setPointScale 1
"Distance Map" seed  showOptionButton 208
"Distance Map" seed  setNumPoints 1 -1 -1
"Distance Map" seed  setCoord 0 1 1 1
"Distance Map" applyTransformToResult 1
"Distance Map" fire
"Distance Map" setViewerMask 16383
"Distance Map" setPickable 1

set hideNewModules 0
[ "Distance Map" create 0 ] setLabel "foam.DistField"
"foam.DistField" setIconPosition 20 118
"foam.DistField" master connect "Distance Map" "result"
"foam.DistField" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.DistField" sharedColormap setDefaultAlpha 0.500000
"foam.DistField" sharedColormap setLocalRange 1
"foam.DistField" sharedColormap setLocalMinMax 0.000000 1.000000
"foam.DistField" sharedColormap enableAlpha 1
"foam.DistField" sharedColormap enableAlphaToggle 1
"foam.DistField" sharedColormap setAutoAdjustRangeMode 1
"foam.DistField" sharedColormap setColorbarMinMax 0 19.3907
"foam.DistField" sharedColormap disconnect
"foam.DistField" fire
"foam.DistField" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"foam.DistField" fire
"foam.DistField" setViewerMask 16383

set hideNewModules 0
create HxContourTreeSegmentation "ContourTreeSegmentation"
"ContourTreeSegmentation" setIconPosition 160 154
"ContourTreeSegmentation" setVar "CustomHelp" {HxContourTreeSegmentation}
"ContourTreeSegmentation" data connect "foam.DistField"
"ContourTreeSegmentation" fire
"ContourTreeSegmentation" auto-initialization setValue 0 1
"ContourTreeSegmentation" auto-initialization setToggleVisible 0 1
"ContourTreeSegmentation" threshold setMinMax 0 19.3907203674316
"ContourTreeSegmentation" threshold setButtons 0
"ContourTreeSegmentation" threshold setEditButton 1
"ContourTreeSegmentation" threshold setIncrement 1.29271
"ContourTreeSegmentation" threshold setValue 0.001
"ContourTreeSegmentation" threshold setSubMinMax 0 19.3907203674316
"ContourTreeSegmentation" persistenceMode setValue 0
"ContourTreeSegmentation" persistenceOptions setValue 0
"ContourTreeSegmentation" persistenceValue setMinMax 0 19.3907203674316
"ContourTreeSegmentation" persistenceValue setButtons 0
"ContourTreeSegmentation" persistenceValue setEditButton 1
"ContourTreeSegmentation" persistenceValue setIncrement 1.29271
"ContourTreeSegmentation" persistenceValue setValue 1.5
"ContourTreeSegmentation" persistenceValue setSubMinMax 0 19.3907203674316
"ContourTreeSegmentation" sortNeighborsBy setValue 1
"ContourTreeSegmentation" fastSegmentation setValue 0 1
"ContourTreeSegmentation" fastSegmentation setToggleVisible 0 1
"ContourTreeSegmentation" applyTransformToResult 1
"ContourTreeSegmentation" fire
"ContourTreeSegmentation" setViewerMask 16383
"ContourTreeSegmentation" select
"ContourTreeSegmentation" setPickable 1
"ContourTreeSegmentation" doIt snap 0 1

set hideNewModules 0
#[ {ContourTreeSegmentation} create result ] setLabel "foam.segmentation"
[ {ContourTreeSegmentation} doIt hit; {ContourTreeSegmentation} fire; {ContourTreeSegmentation} getResult
 ] setLabel "foam.segmentation"
"foam.segmentation" setIconPosition 20 190
"foam.segmentation" master connect "ContourTreeSegmentation" "result"
"foam.segmentation" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.segmentation" sharedColormap setDefaultAlpha 0.500000
"foam.segmentation" sharedColormap setLocalRange 1
"foam.segmentation" sharedColormap setLocalMinMax 0.000000 1.000000
"foam.segmentation" sharedColormap enableAlpha 1
"foam.segmentation" sharedColormap enableAlphaToggle 1
"foam.segmentation" sharedColormap setAutoAdjustRangeMode 1
"foam.segmentation" sharedColormap setColorbarMinMax 0 119
"foam.segmentation" sharedColormap disconnect
"foam.segmentation" fire
"foam.segmentation" fire
"foam.segmentation" setViewerMask 16383

set hideNewModules 0
create HxCastField "Convert Image Type"
"Convert Image Type" setIconPosition 160 226
"Convert Image Type" setVar "CustomHelp" {HxCastField}
"Convert Image Type" data connect "foam.segmentation"
"Convert Image Type" colormap setDefaultColor 1 0.8 0.5
"Convert Image Type" colormap setDefaultAlpha 0.500000
"Convert Image Type" colormap setLocalRange 1
"Convert Image Type" colormap setLocalMinMax 0.000000 119.000000
"Convert Image Type" colormap enableAlpha 1
"Convert Image Type" colormap enableAlphaToggle 1
"Convert Image Type" colormap setAutoAdjustRangeMode 1
"Convert Image Type" colormap setColorbarMinMax 0 119
"Convert Image Type" colormap disconnect
"Convert Image Type" fire
"Convert Image Type" outputType setIndex 0 7
"Convert Image Type" scaling setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
"Convert Image Type" scaling setValue 0 1
"Convert Image Type" scaling setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
"Convert Image Type" scaling setValue 1 0
"Convert Image Type" voxelGridOptions setValue 0 1
"Convert Image Type" voxelGridOptions setToggleVisible 0 1
"Convert Image Type" colorFieldOptions setIndex 0 0
"Convert Image Type" applyTransformToResult 1
"Convert Image Type" fire
"Convert Image Type" setViewerMask 16383
"Convert Image Type" setPickable 1
"Convert Image Type" action snap 0 1

set hideNewModules 0
[ {Convert Image Type} create result ] setLabel "foam.to-labelfield-16_bits"
"foam.to-labelfield-16_bits" setIconPosition 20 262
"foam.to-labelfield-16_bits" master connect "Convert Image Type" "result"
"foam.to-labelfield-16_bits" sharedColormap setDefaultColor 0.8 0.8 0.8
"foam.to-labelfield-16_bits" sharedColormap setDefaultAlpha 0.500000
"foam.to-labelfield-16_bits" sharedColormap setLocalRange 1
"foam.to-labelfield-16_bits" sharedColormap setLocalMinMax 1.000000 8.000000
"foam.to-labelfield-16_bits" sharedColormap enableAlpha 1
"foam.to-labelfield-16_bits" sharedColormap enableAlphaToggle 1
"foam.to-labelfield-16_bits" sharedColormap setAutoAdjustRangeMode 1
"foam.to-labelfield-16_bits" sharedColormap setColorbarMinMax 1 8
"foam.to-labelfield-16_bits" sharedColormap connect "labels.am"
"foam.to-labelfield-16_bits" ImageData disconnect
"foam.to-labelfield-16_bits" fire
"foam.to-labelfield-16_bits" primary setIndex 0 0
"foam.to-labelfield-16_bits" fire
"foam.to-labelfield-16_bits" setViewerMask 16383

set hideNewModules 0
create HxGMC "Generate Surface"
"Generate Surface" setIconPosition 160 298
"Generate Surface" setVar "CustomHelp" {HxGMC}
"Generate Surface" data connect "foam.to-labelfield-16_bits"
"Generate Surface" fire
"Generate Surface" smoothing setIndex 0 3
"Generate Surface" smoothingExtent setMinMax 1 9
"Generate Surface" smoothingExtent setButtons 0
"Generate Surface" smoothingExtent setEditButton 1
"Generate Surface" smoothingExtent setIncrement 0.533333
"Generate Surface" smoothingExtent setValue 5
"Generate Surface" smoothingExtent setSubMinMax 1 9
"Generate Surface" options setValue 0 1
"Generate Surface" options setToggleVisible 0 1
"Generate Surface" options setValue 1 0
"Generate Surface" options setToggleVisible 1 1
"Generate Surface" border setValue 0 1
"Generate Surface" border setToggleVisible 0 1
"Generate Surface" border setValue 1 0
"Generate Surface" border setToggleVisible 1 1
"Generate Surface" border setValue 2 0
"Generate Surface" border setToggleVisible 2 1
"Generate Surface" border setValue 3 0
"Generate Surface" border setToggleVisible 3 0
"Generate Surface" minEdgeLength setMinMax 0 0 0.800000011920929
"Generate Surface" minEdgeLength setValue 0 0
"Generate Surface" materialList setIndex 0 0
"Generate Surface" smoothMaterial setIndex 0 0
"Generate Surface" applyTransformToResult 1
"Generate Surface" fire
"Generate Surface" setViewerMask 16383
"Generate Surface" setPickable 1
"Generate Surface" action snap 0 1

set hideNewModules 0
[ "Generate Surface" create "foam.surf"
 ] setLabel "foam.surf"
"foam.surf" setIconPosition 20 298
"foam.surf" master connect "Generate Surface" "result"
"foam.surf" fire
"foam.surf" LevelOfDetail setMinMax -1 -1
"foam.surf" LevelOfDetail setButtons 1
"foam.surf" LevelOfDetail setEditButton 1
"foam.surf" LevelOfDetail setIncrement 1
"foam.surf" LevelOfDetail setValue -1
"foam.surf" LevelOfDetail setSubMinMax -1 -1
"foam.surf" fire
"foam.surf" setViewerMask 16383

set hideNewModules 0
create HxDisplaySurface "Surface View"
"Surface View" setIconPosition 372 298
"Surface View" setVar "CustomHelp" {HxDisplaySurface}
"Surface View" data connect "foam.surf"
"Surface View" colorField disconnect
"Surface View" colormap setDefaultColor 1 0.1 0.1
"Surface View" colormap setDefaultAlpha 0.500000
"Surface View" colormap setLocalRange 1
"Surface View" colormap setLocalMinMax 0.000000 1.000000
"Surface View" colormap enableAlpha 1
"Surface View" colormap enableAlphaToggle 1
"Surface View" colormap setAutoAdjustRangeMode 1
"Surface View" colormap setColorbarMinMax 0 1
"Surface View" colormap disconnect
"Surface View" Texture disconnect
"Surface View" ROI disconnect
"Surface View" fire
"Surface View" drawStyle setValue 1
"Surface View" fire
"Surface View" drawStyle setSpecularLighting 1
"Surface View" drawStyle setTexture 1
"Surface View" drawStyle setAlphaMode 1
"Surface View" drawStyle setNormalBinding 0
"Surface View" drawStyle setSortingMode 1
"Surface View" drawStyle setLineWidth 0.000000
"Surface View" drawStyle setOutlineColor 0 0 0.2
"Surface View" textureWrap setIndex 0 1
"Surface View" cullingMode setValue 0
"Surface View" selectionMode setIndex 0 0
"Surface View" Patch setMinMax 0 355
"Surface View" Patch setButtons 1
"Surface View" Patch setEditButton 1
"Surface View" Patch setIncrement 1
"Surface View" Patch setValue 0
"Surface View" Patch setSubMinMax 0 355
"Surface View" BoundaryId setIndex 0 -1
"Surface View" materials setIndex 0 1
"Surface View" materials setIndex 1 0
"Surface View" colorMode setIndex 0 0
"Surface View" baseTrans setMinMax 0 1
"Surface View" baseTrans setButtons 0
"Surface View" baseTrans setEditButton 1
"Surface View" baseTrans setIncrement 0.1
"Surface View" baseTrans setValue 0.8
"Surface View" baseTrans setSubMinMax 0 1
"Surface View" VRMode setIndex 0 0
"Surface View" colorFieldMappingType setValue 0
"Surface View" setLighting 1
"Surface View" fire
"Surface View" hideBox 1
"Surface View" selectTriangles zab HIJMONNNFNGOICEABAAAOAEJDMEAIPMENFDJBCAHDANJICBGILLEMCKKCAHPNPJHPIOAILOCAKMDDCOMAMCJABMALNIIOGHFFFLPDNCPLNDNAAAALAAGBBMFGNJONMKIKOPDGFAADGKGMNHLKEFCBMAHAAAAGADNLKPHOJPPJDNCNJHFCMMAIKNFKBPKGLCIIOOHKKDPKKFKPKLHAAAMKJMDJNHJCLAAAAAAAAAALDOJNHGPGFNMFPCLJHNOGGAAGAHODPDHKCJNPHIBNNKLCPIJJOLKCGLKFNBLIFJKOJDFPIEKHHLNPLKMAHAFAAAAAAIAJFGLNHKJOIELAJAAAAOMEBOOFKPMKFLHBDNIJHIIFDLCIGGNDJEFHKLMOGFACPDAAAAAAAOAEINKNKLOJECKDJBBCAMLFIENHHCJOPANAAAAEPILNOHDBMKNCHABAANILPHKMKFHOENEDBPEGKBKPEBHEOODMPAFNOJKPKCHJNJHBOFDPIMPFILNJFFOBDAAODOCPEFKMPPELPPDIFHCPCJINLHMOKJPOPKJMEHGPCNNOKCDGHNIDPBPHPOHDEMHNEJMMMJBNIKKBIMIFDDIDPLAHGONDJGJPCJIHOLGOPOHIICGFJKHDGBPAAJIFIFMJHNABNFOPCBMDPGAGFHCNGGLCMLNINFLNHAMGAHHDMCLGDMKIBPFIPIHKOLDGDADIAAMNBKLNHHLJFDKDPNIKPLBPODJIDLBEBANMAKGHNHKBNFKLCLPAAAHDGJEODPJINJDHKGAMOOBJNLJEOOGPJINDHFMAGLADEIOHLBBBDOFCABOBMGLNGANAAEMGEKOLKIDLNNKECINMACLPPKJHLMNHJNKPMFJGJLMDOOKJJFODKJPKMHJGKKOCPNHHCONBOAPOGNOJPKMHDGGFKPFNPHHHKDGJGEPKFAMDBOOFNEFLKMPDPCFLNNBAOKFEIOPOFBPIPBMLLLDPCOGKFBINFNHDOFHGLHILPFKMHJMIFGBKDHNONHGHCHPDNEGPCMGGFKMOHDIIPMLKEHPPKONJJKLFPGIDHEGDGLNLNMEEMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAELCCCOEPGAOKLMEPOJBLGCFHIINH
"Surface View" fire
"Surface View" setViewerMask 16383
"Surface View" setShadowStyle 0
"Surface View" setPickable 1

set hideNewModules 0

viewer 1 setCameraOrientation -0.887541 0.390968 -0.243752 2.2205
viewer 1 setCameraPosition 385.064 329.943 -145.681
viewer 1 setCameraFocalDistance 366.025
viewer 1 setCameraNearDistance 207.58
viewer 1 setCameraFarDistance 524.786
viewer 1 setCameraType perspective
viewer 1 setCameraHeightAngle 44.9023
viewer 1 setAutoRedraw 1
viewer 1 redraw

"Interactive Thresholding" sliceNumber interconnect "Interactive Thresholding_HxOrthoSlice" sliceNumber
theObjectPool setSelectionOrder ContourTreeSegmentation
