// AUTOMATICALLY GENERATED BY CMAKE. DO NOT MODIFY.
#ifndef HXFILOPODIA_API_EXPORT_MACRO_H
#define HXFILOPODIA_API_EXPORT_MACRO_H

#ifdef HXFILOPODIA_STATIC
#   define HXFILOPODIA_API
#else
#   ifdef _WIN32
#       ifdef HXFILOPODIA_EXPORTS
#           define HXFILOPODIA_API __declspec(dllexport)
#       else
#           define HXFILOPODIA_API __declspec(dllimport)
#       endif
#   else
#       define HXFILOPODIA_API __attribute__ ((visibility("default")))
#   endif
#endif

#endif
