// AUTOMATICALLY GENERATED BY CMAKE. DO NOT MODIFY.
#ifndef POINTMATCHING_API_EXPORT_MACRO_H
#define POINTMATCHING_API_EXPORT_MACRO_H

#ifdef POINTMATCHING_STATIC
#   define POINTMATCHING_API
#else
#   ifdef _WIN32
#       ifdef POINTMATCHING_EXPORTS
#           define POINTMATCHING_API __declspec(dllexport)
#       else
#           define POINTMATCHING_API __declspec(dllimport)
#       endif
#   else
#       define POINTMATCHING_API __attribute__ ((visibility("default")))
#   endif
#endif

#endif
